##INSERTION DES DONNÉES DANS LA TABLE tblVille

USE BD_Aeroport_2018;

INSERT INTO tblVille VALUES
("AAE","Annaba","DZ"),
("AAL","Aalborg","DK"),
("AAR","Aarhus","DK"),
("ABJ","Abidjan","CI"),
("ABQ","Albuquerque","US"),
("ABS","Abou Simbel","EG"),
("ABV","Abuja","NG"),
("ABZ","Aberdeen","GB"),
("ACA","Acapulco","MX"),
("ACC","Accra","GH"),
("ACE","Arrecife","ES"),
("ADD","Addis Abeba","ET"),
("ADE","Aden","YE"),
("ADL","Adelaide","AU"),
("ADZ","San Andres Island","CO"),
("AGA","Agadir","MA"),
("AGF","Agen","FR"),
("AGP","Malaga","ES"),
("AGR","Agra","IN"),
("AHO","Alghero","IT"),
("AJA","Ajaccio","FR"),
("AJN","Anjouan","KM"),
("AJY","Agades","NE"),
("AKL","Auckland","NZ"),
("ALA","Almaty","KZ"),
("ALC","Alicante","ES"),
("ALG","Alger","DZ"),
("ALI","Al Ain","AE"),
("ALP","Alep","SY"),
("ALY","Alexandrie","EG"),
("AMD","Ahmadabad","IN"),
("AMI","Mataram","ID"),
("AMM","Amman","JO"),
("AMS","Amsterdam","NL"),
("ANC","Anchorage","US"),
("ANE","Angers","FR"),
("ANF","Antofagasta","CL"),
("ANG","Angouleme","FR"),
("ANK","Ankara","TR"),
("ANR","Anvers","BE"),
("ANU","Antigua","AG"),
("APW","Apia","WS"),
("AQJ","Aqaba","JO"),
("AQP","Arequipa","PE"),
("ARK","Arusha","TZ"),
("ASB","Ashkhabad","TM"),
("ASD","Andros Town","BS"),
("ASM","Asmara","ER"),
("ASP","Alice Springs","AU"),
("ASU","Asuncion","PY"),
("ASW","Assouan","EG"),
("ATH","Athenes","GR"),
("ATL","Atlanta","US"),
("ATQ","Amritsar","IN"),
("ATR","Atar","MR"),
("AUA","Oranjestad","AW"),
("AUF","Auxerre","FR"),
("AUH","Abou Dhabi","AE"),
("AUR","Aurillac","FR"),
("AVN","Avignon","FR"),
("AXA","Anguilla","AI"),
("AYQ","Ayers Rock","AU"),
("AYT","Antalya","TR"),
("BAH","Bahrein","BH"),
("BAK","Bakou","AZ"),
("BBK","Kasane","BW"),
("BBQ","Barbuda","AG"),
("BBR","Basse-Terre","GP"),
("BBZ","Zambezi","ZM"),
("BCN","Barcelone","ES"),
("BDA","Bermude","BM"),
("BDS","Brindisi","IT"),
("BEG","Belgrade","RS"),
("BEL","Belem","BR"),
("BEN","Benghazi","LY"),
("BER","Berlin","DE"),
("BES","Brest","FR"),
("BEW","Beira","MZ"),
("BEY","Beyrouth","LB"),
("BFS","Belfast","GB"),
("BGF","Bangui","CF"),
("BGI","Bridgetown","BB"),
("BGO","Bergen","NO"),
("BGW","Bagdad","IQ"),
("BGY","Bergame","IT"),
("BGZ","Braga","PT"),
("BHK","Bukhara","UZ"),
("BHX","Birmingham","GB"),
("BHZ","Belo Horizonte","BR"),
("BIA","Bastia","FR"),
("BIO","Bilbao","ES"),
("BIQ","Biarritz","FR"),
("BJA","Bejaia","DZ"),
("BJC","Broomfield","US"),
("BJL","Banjul","GM"),
("BJM","Bujumbura","BI"),
("BKI","Kota Kinabalu","MY"),
("BKK","Bangkok","TH"),
("BKL","Cleveland","US"),
("BKO","Bamako","ML"),
("BLA","Barcelona","VE"),
("BLL","Billund","DK"),
("BLQ","Bologne","IT"),
("BLZ","Blantyre","MW"),
("BNE","Brisbane","AU"),
("BNJ","Bonn","DE"),
("BOB","Bora Bora","PF"),
("BOD","Bordeaux","FR"),
("BOG","Bogota","CO"),
("BOH","Bournemouth","GB"),
("BOJ","Bourgas","BG"),
("BOM","Bombay","IN"),
("BON","Bonaire","BQ"),
("BOO","Bodo","NO"),
("BOS","Boston","US"),
("BQE","Bubaque","GW"),
("BQU","Bequia","VC"),
("BRC","San Carlos de Bariloche","AR"),
("BRE","Bremen","DE"),
("BRI","Bari","IT"),
("BRN","Berne","CH"),
("BRQ","Brno","CZ"),
("BRS","Bristol","GB"),
("BRU","Bruxelles","BE"),
("BRX","Barahona","DO"),
("BSB","Brasilia","BR"),
("BSG","Bata","GQ"),
("BSK","Biskra","DZ"),
("BSL","Bale","CH"),
("BTS","Bratislava","SK"),
("BUA","Buariki","KI"),
("BUD","Budapest","HU"),
("BUE","Buenos Aires","AR"),
("BUH","Bucarest","RO"),
("BVA","Beauvais","FR"),
("BVB","Boa Vista","BR"),
("BVC","Boavista","CV"),
("BVE","Brive","FR"),
("BWI","Baltimore","US"),
("BWN","Bandar Seri Begawan","BN"),
("BXO","Bissau","GW"),
("BZE","Belize","BZ"),
("BZR","Beziers","FR"),
("CAG","Cagliari","IT"),
("CAI","Le Caire","EG"),
("CAN","Guangzhou","CN"),
("CAP","Cap Haitien","HT"),
("CAS","Casablanca","MA"),
("CAY","Cayenne","GY"),
("CBR","Canberra","AU"),
("CCC","Cayo Coco","CU"),
("CCE","Saint Martin","GP"),
("CCF","Carcassonne","FR"),
("CCS","Caracas","VE"),
("CCU","Calcutta","IN"),
("CEB","Cebu","PH"),
("CEI","Chiang Rai","TH"),
("CEQ","Cannes","FR"),
("CER","Cherbourg","FR"),
("CFE","Clermont-Ferrand","FR"),
("CFG","Cienfuegos","CU"),
("CFR","Caen","FR"),
("CGN","Cologne","DE"),
("CGO","Zhengzhou","CN"),
("CGP","Chittagong","BD"),
("CGT","Chinguitti","MR"),
("CHC","Christchurch","NZ"),
("CHH","Chachapoyas","PE"),
("CHI","Chicago","US"),
("CHR","Chateauroux","FR"),
("CHS","Charleston","US"),
("CLY","Calvi","FR"),
("CMB","Colombo","LK"),
("CMF","Chambery","FR"),
("CMR","Colmar","FR"),
("CND","Constanza","RO"),
("CNG","Cognac","FR"),
("CNS","Cairns","AU"),
("COO","Cotonou","BJ"),
("CPD","Coober Pedy","AU"),
("CPE","Campeche","MX"),
("CPH","Copenhague","DK"),
("CPT","Cape Town","ZA"),
("CRK","Luzon","PH"),
("CRL","Charleroi","BE"),
("CSK","Cap Skirring","SN"),
("CTA","Catane","IT"),
("CTG","Cartagena","CO"),
("CTU","Chengdu","CN"),
("CUE","Cuenca","EC"),
("CUK","Caye Caulker","BZ"),
("CUN","Cancun","MX"),
("CUR","Curacao","CW"),
("CUZ","Cuzco","PE"),
("CWL","Cardiff","GB"),
("CZL","Constantine","DZ"),
("CZM","Cozumel","MX"),
("CZW","Czestochowa","PL"),
("CZX","Changzhou","CN"),
("DAC","Dhaka","BD"),
("DAD","Da Nang","VN"),
("DAL","Dallas","US"),
("DAM","Damas","SY"),
("DAR","Dar es Salaam","TZ"),
("DBV","Dubrovnik","HR"),
("DCM","Castres","FR"),
("DDM","Dodoma","TZ"),
("DEL","Delhi","IN"),
("DEN","Denver","US"),
("DET","Detroit","US"),
("DFW","Fort Worth","US"),
("DHM","Dharamsala","IN"),
("DIJ","Dijon","FR"),
("DIL","Dili","TL"),
("DIR","Dire Dawa","ET"),
("DJE","Djerba/Zarzis","TN"),
("DJG","Djanet","DZ"),
("DKR","Dakar","SN"),
("DLA","Douala","CM"),
("DLM","Dalaman","TR"),
("DNK","Dnipropetrovsk","UA"),
("DNR","Dinard","FR"),
("DOH","Doha","QA"),
("DOL","Deauville","FR"),
("DPS","Denpasar","ID"),
("DRS","Dresde","DE"),
("DRW","Darwin","AU"),
("DSA","Doncaster/Sheffield","GB"),
("DSD","La Désirade","GP"),
("DTH","Death Valley","US"),
("DTM","Dortmund","DE"),
("DUB","Dublin","IE"),
("DUR","Durban","ZA"),
("DUS","Dusseldorf","DE"),
("DXB","Dubai","AE"),
("DYU","Dushanbe","TJ"),
("DZA","Dzaoudzi","YT"),
("EAM","Mulhouse","FR"),
("EAS","San Sebastian","ES"),
("EBB","Kampala","UG"),
("EBU","Saint-Etienne","FR"),
("EDI","Edimbourg","GB"),
("EGC","Bergerac","FR"),
("EIN","Eindhoven","NL"),
("ELP","El Paso","US"),
("ELS","East London","ZA"),
("EMA","East Midlands","GB"),
("ENC","Nancy","FR"),
("EPS","Santa Barbara de Samana","DO"),
("ERI","Erie","US"),
("ETZ","Metz","FR"),
("EVN","Erevan","AM"),
("EWR","Newark","US"),
("EXT","Exeter","GB"),
("EYW","Key West","US"),
("FAI","Fairbanks","US"),
("FAO","Faro","PT"),
("FAR","Fargo","US"),
("FBM","Lubumbashi","CD"),
("FDF","Fort-de-France","MQ"),
("FDH","Friedrichshafen","DE"),
("FEZ","Fes","MA"),
("FIH","Kinshasa","CD"),
("FJR","Fujairah","AE"),
("FLL","Fort Lauderdale","US"),
("FLR","Florence","IT"),
("FNA","Freetown","SL"),
("FNC","Funchal","PT"),
("FNI","Nimes/Arles","FR"),
("FNJ","Pyongyang","KP"),
("FNT","Flint","US"),
("FOR","Fortaleza","BR"),
("FPO","Freeport","BS"),
("FRA","Francfort","DE"),
("FRS","Flores","GT"),
("FRU","Bishkek","KG"),
("FSC","Figari","FR"),
("FTU","Fort Dauphin","MG"),
("FUE","Fuerteventura","ES"),
("FUK","Fukuoka","JP"),
("FWA","Fort Wayne","US"),
("GAE","Gabes","TN"),
("GAF","Gafsa","TN"),
("GAN","Ile de Gan","MV"),
("GAQ","Gao","ML"),
("GBE","Gaborone","BW"),
("GBJ","Marie Galante","GP"),
("GCI","Guernesey","GG"),
("GCM","Grand Cayman","KY"),
("GDL","Guadalajara","MX"),
("GDN","Gdansk","PL"),
("GDT","Grand Turk","TC"),
("GEO","Georgetown","GY"),
("GHA","Ghardaia","DZ"),
("GIB","Gibraltar","GI"),
("GLA","Glasgow","GB"),
("GNB","Grenoble","FR"),
("GND","Grenade","GD"),
("GOI","Goa","IN"),
("GOQ","Golmud","CN"),
("GOT","Goteborg","SE"),
("GOU","Garoua","CM"),
("GPS","Galapagos Islands","EC"),
("GRO","Gerona","ES"),
("GRW","Graciosa Island","PT"),
("GRX","Granada","ES"),
("GRZ","Graz","AT"),
("GTN","Mount Cook","NZ"),
("GUA","Guatemala City","GT"),
("GUM","Guam","GU"),
("GVA","Geneve","CH"),
("GWY","Galway","IE"),
("GYE","Guayaquil","EC"),
("GZA","Gaza","PS"),
("GZM","Gozo","MT"),
("HAH","Moroni","KM"),
("HAJ","Hannovre","DE"),
("HAM","Hamburg","DE"),
("HAN","Hanoi","VN"),
("HAV","La Havane","CU"),
("HBA","Hobart","AU"),
("HEL","Helsinki","FI"),
("HER","Heraklion","GR"),
("HFA","Haifa","IL"),
("HHN","Hahn","DE"),
("HIR","Honiara","SB"),
("HIX","Hiva Oa","PF"),
("HKG","Hong Kong","HK"),
("HKT","Phuket","TH"),
("HNL","Honolulu","US"),
("HOG","Holguin","CU"),
("HOR","Horta","PT"),
("HOU","Houston","US"),
("HRE","Harare","ZW"),
("HRG","Hurghada","EG"),
("HTB","Terre de Bas","GP"),
("HUY","Humberside","GB"),
("HYD","Hyderabad","IN"),
("IDY","Ile d'Yeu","FR"),
("IEV","Kiev","UA"),
("IFN","Isfahan","IR"),
("IGR","Iguazu","AR"),
("IGU","Foz do Iguacu","BR"),
("IKT","Irkutsk","RU"),
("ILP","Ile des Pins","NC"),
("IND","Indianapolis","US"),
("INN","Innsbruck","AT"),
("INU","Nauru","NR"),
("INV","Inverness","GB"),
("IOM","Isle of Man","GB"),
("IQT","Iquitos","PE"),
("IST","Istanbul","TR"),
("IXL","Leh","IN"),
("IZM","Izmir","TR"),
("JAX","Jacksonville","US"),
("JED","Jeddah","SA"),
("JFM","Fremantle","AU"),
("JHB","Johor Bahru","MY"),
("JIB","Djibouti","DJ"),
("JKT","Jakarta","ID"),
("JMK","Mykonos","GR"),
("JNB","Johannesburg","ZA"),
("JOG","Yogyakarta","ID"),
("JRO","Kilimanjaro","TZ"),
("JUL","Juliaca","PE"),
("KBL","Kaboul","AF"),
("KCH","Kuching","MY"),
("KDH","Kandahar","AF"),
("KGL","Kigali","RW"),
("KHH","Kaohsiung","TW"),
("KHI","Karachi","PK"),
("KIN","Kingston","JM"),
("KIV","Chisinau","MD"),
("KNO","Medan","ID"),
("KRK","Krakow","PL"),
("KRT","Khartoum","SD"),
("KTM","Katmandou","NP"),
("KUL","Kuala Lumpur","MY"),
("KWI","Koweit City","KW"),
("LAD","Luanda","AO"),
("LAX","Los Angeles","US"),
("LBA","Leeds/Bradford","GB"),
("LBV","Libreville","GA"),
("LBY","La Baule","FR"),
("LCA","Larnaca","CY"),
("LED","St. Petersburg","RU"),
("LFW","Lome","TG"),
("LGG","Liege","BE"),
("LGK","Langkawi","MY"),
("LHE","Lahore","PK"),
("LIL","Lille","FR"),
("LIM","Lima","PE"),
("LIS","Lisbone","PT"),
("LJU","Ljubljana","SI"),
("LLW","Lilongwe","MW"),
("LON","Londres","GB"),
("LOS","Lagos","NG"),
("LPA","Las Palmas","ES"),
("LPB","La Paz","BO"),
("LPL","Liverpool","GB"),
("LPQ","Luang Prabang","LA"),
("LRM","La Romana","DO"),
("LTN","Luton","GB"),
("LUG","Lugano","CH"),
("LUN","Lusaka ","ZM"),
("LUX","Luxembourg","LU"),
("LVS","Las Vegas","US"),
("LXA","Lhasa","CN"),
("LXR","Luxor","EG"),
("LYR","Svalbard","NO"),
("MAA","Madras","IN"),
("MAD","Madrid","ES"),
("MAN","Manchester","GB"),
("MAO","Manaus","BR"),
("MBA","Mombasa","KE"),
("MBJ","Montego Bay","JM"),
("MCT","Muscat","OM"),
("MCZ","Maceio","BR"),
("MDE","Medellin","CO"),
("MDL","Mandalay","MM"),
("MED","Medine","SA"),
("MEL","Melbourne","AU"),
("MEM","Memphis","US"),
("MEX","Mexico City","MX"),
("MFM","Macao","CN"),
("MGA","Managua","NI"),
("MGQ","Mogadiscio","SO"),
("MIA","Miami","US"),
("MIL","Milan","IT"),
("MIR","Monastir","TN"),
("MKE","Milwaukee","US"),
("MLA","Malte","MT"),
("MLE","Male","MV"),
("MLW","Monrovia","LR"),
("MMX","Malmo","SE"),
("MMK","Murmansk","RU"),
("MMO","Maio","CV"),
("MNL","Manille","PH"),
("MOW","Moscou","RU"),
("MPM","Maputo","MZ"),
("MPN","Mount Pleasant","FK"),
("MRD","Merida","VE"),
("MRS","Marseille","FR"),
("MRU","Plaisance","MU"),
("MRX","Margarita Island","VE"),
("MSP","Minneapolis/St. Paul","US"),
("MSQ","Minsk","BY"),
("MST","Maastricht","NL"),
("MSU","Maseru","LS"),
("MSW","Massawa","ER"),
("MTL","Montreal","CA"),
("MTY","Monterrey","MX"),
("MUB","Maun","BW"),
("MUC","Munich","DE"),
("MVD","Montevideo","UY"),
("MZI","Mopti","ML"),
("NAN","Nadi","FJ"),
("NAP","Naples","IT"),
("NAS","Nassau","BS"),
("NAT","Natal","BR"),
("NBL","San Blas","PA"),
("NBO","Nairobi","KE"),
("NCE","Nice","FR"),
("NCL","Newcastle","GB"),
("NDJ","N'Djamena","TD"),
("NEW","Nouvelle-Orleans","US"),
("NGO","Nagoya","JP"),
("NGS","Nagasaki","JP"),
("NIC","Nicosie","CY"),
("NIM","Niamey","NE"),
("NKC","Nouakchott","MR"),
("NKM","Nagoya","JP"),
("NOS","Nossi-Be","MG"),
("NOU","Noumea","NC"),
("NTE","Nantes","FR"),
("NTO","Santo Antao","CV"),
("NWA","Moheli","KM"),
("NWI","Norwich","GB"),
("NYC","New York","US"),
("OAK","Oakland","US"),
("ODB","Cordou","ES"),
("ODE","Odense","DK"),
("ODS","Odessa","UA"),
("OHD","Ohrid","MK"),
("OLB","Olbia","IT"),
("OMO","Mostar","BA"),
("OOL","Coolangata","AU"),
("OPO","Porto","PT"),
("ORA","Oran","DZ"),
("ORK","Cork","IE"),
("OSA","Osaka","JP"),
("OSL","Oslo","NO"),
("OSS","Osh","KG"),
("OST","Ostende","BE"),
("OUA","Ouagadougou","BF"),
("PAC","Panama City","PA"),
("PAP","Port-au-Prince","HT"),
("PAR","Paris","FR"),
("PAS","Paros","GR"),
("PBC","Puebla","MX"),
("PBG","Plattsburgh","US"),
("PBH","Paro","BT"),
("PBM","Paramaribo","SR"),
("PCP","Principe","ST"),
("PDX","Portland","US"),
("PEK","Beijing","CN"),
("PEN","Penang","MY"),
("PER","Perth","AU"),
("PEW","Peshawar","PK"),
("PFO","Paphos","CY"),
("PHC","Port Harcourt","NG"),
("PHL","Philadelphie","US"),
("PHW","Phalaborwa","ZA"),
("PHX","Phoenix","US"),
("PIT","Pittsburgh","US"),
("PMA","Pemba Island","TZ"),
("PMC","Puerto Montt","CL"),
("PMF","Parme","IT"),
("PMI","Palma de Mallorca","ES"),
("PMO","Palerme","IT"),
("PNA","Pampelune","ES"),
("PNH","Phnom Penh","KH"),
("PNI","Pohnpei","FM"),
("PNR","Pointe Noire","CG"),
("POA","Porto Alegre","BR"),
("POI","Potosi","BO"),
("POL","Pemba","MZ"),
("POM","Port Moresby","PG"),
("POP","Puerto Plata","DO"),
("POS","Port of Spain","TT"),
("PPG","Pago Pago","AS"),
("PPS","Puerto Princesa","PH"),
("PPT","Papeete","PF"),
("PRG","Prague","CZ"),
("PRI","Praslin","SC"),
("PRJ","Capri","IT"),
("PSA","Pise","IT"),
("PSY","Port Stanley","FK"),
("PTP","Pointe-a-Pitre","GP"),
("PUJ","Punta Cana","DO"),
("PUS","Pusan","KR"),
("PVR","Puerto Vallarta","MX"),
("PYX","Pattaya","TH"),
("PZU","Port Soudan","SD"),
("QLJ","Lucerne","CH"),
("QLS","Lausanne","CH"),
("QPA","Padoue","IT"),
("QSO","Sousse","TN"),
("QTW","Taejon","KR"),
("RAI","Praia","CV"),
("RAK","Marrakech","MA"),
("RBA","Rabat","MA"),
("RDU","Raleigh-Durham","US"),
("RDZ","Rodez","FR"),
("REC","Recife","BR"),
("REK","Reykjavik","IS"),
("REP","Siem Reap","KH"),
("RGN","Rangoon","MM"),
("RHE","Reims","FR"),
("RHO","Rhodes","GR"),
("RIO","Rio de Janeiro","BR"),
("RIX","Riga","LV"),
("RJK","Rijeka","HR"),
("RNS","Rennes","FR"),
("ROM","Rome","IT"),
("RTB","Roatan","HN"),
("RTM","Rotterdam","NL"),
("RUH","Riyadh","SA"),
("RUN","Saint-Denis","RE"),
("RUY","Copan","HN"),
("RVN","Rovaniemi","FI"),
("RWP","Rawalpindi","PK"),
("SAB","Saba","BQ"),
("SAH","Sana'a","YE"),
("SAL","San Salvador","SV"),
("SAO","Sao Paulo","BR"),
("SAP","San Pedro Sula","HN"),
("SAT","San Antonio","US"),
("SBH","Saint Barthelemy","GP"),
("SBK","Saint Brieuc","FR"),
("SCL","Santiago","CL"),
("SCN","Saarbrucken","DE"),
("SCQ","Santiago Compostela","ES"),
("SCU","Santiago","CU"),
("SDQ","Santo Domingo","DO"),
("SEA","Seattle","US"),
("SEL","Seoul","KR"),
("SEZ","Mahe","SC"),
("SFA","Sfax","TN"),
("SFJ","Kangerlussuaq","GL"),
("SFO","San Francisco","US"),
("SGN","Ho Chi Minh Ville","VN"),
("SHA","Shanghai","CN"),
("SHJ","Sharjah","AE"),
("SIA","Xian","CN"),
("SID","Sal","CV"),
("SII","Sidi Ifni","MA"),
("SIN","Singapour","SG"),
("SIR","Sion","CH"),
("SJD","Los Cabos","MX"),
("SJJ","Sarajevo","BA"),
("SJO","San Jose","CR"),
("SJU","San Juan","PR"),
("SJZ","Sao Jorge","PT"),
("SKD","Samarkand","UZ"),
("SKG","Thessalonique","GR"),
("SKI","Skikda","DZ"),
("SKL","Isle of Skye","GB"),
("SKP","Skopje","MK"),
("SKU","Skiros","GR"),
("SLC","Salt Lake City","US"),
("SLZ","Sao Luis","BR"),
("SMR","Santa Marta","CO"),
("SMS","Ste Marie","MG"),
("SNE","Sao Nicolau","CV"),
("SNN","Shannon","IE"),
("SOF","Sofia","BG"),
("SOU","Southampton","GB"),
("SPK","Saporro","JP"),
("SPN","Saipan","MP"),
("SPU","Split","HR"),
("SRE","Sucre","BO"),
("SSA","Salvador","BR"),
("SSG","Malabo","GQ"),
("SSH","Sharm El Sheikh","EG"),
("STL","St. Louis","US"),
("STM","Santarem","BR"),
("STO","Stockholm","SE"),
("STR","Stuttgart","DE"),
("SUB","Surabaya","ID"),
("SUV","Suva","FJ"),
("SVG","Stavanger","NO"),
("SVQ","Seville","ES"),
("SWP","Swakopmund","NA"),
("SXB","Strasbourg","FR"),
("SXM","St. Martin","SX"),
("SYD","Sydney","AU"),
("SYZ","Shiraz","IR"),
("SZG","Salzburg","AT"),
("SZX","Shenzhen","CN"),
("TAB","Tobago","TT"),
("TAH","Tanna Island","VU"),
("TAS","Tashkent","UZ"),
("TBS","Tbilisi","GE"),
("TBZ","Tabriz","IR"),
("TCP","Taba","EG"),
("TDD","Trinidad","BO"),
("TER","Terceira","PT"),
("TFN","Tenerife","ES"),
("TFR","Tarbes","FR"),
("TGU","Tegucigalpa","HN"),
("THR","Teheran","IR"),
("TIA","Tirana","AL"),
("TIP","Tripoli","LY"),
("TKU","Turku","FI"),
("TLC","Toluca","MX"),
("TLE","Tulear","MG"),
("TLL","Tallinn","EE"),
("TLN","Toulon","FR"),
("TLS","Toulouse","FR"),
("TLV","Tel Aviv","IL"),
("TMM","Tamatave","MG"),
("TMP","Tampere","FI"),
("TMR","Tamanrasset","DZ"),
("TMS","Sao Tome","ST"),
("TNG","Tanger","MA"),
("TNR","Antananarivo","MG"),
("TOD","Tioman","MY"),
("TOE","Tozeur","TN"),
("TOM","Tombouctou","ML"),
("TPE","Taipei","TW"),
("TRD","Trondheim","NO"),
("TRN","Turin","IT"),
("TRS","Trieste","IT"),
("TRU","Trujillo","PE"),
("TRV","Trivandrum","IN"),
("TSE","Astana","KZ"),
("TSF","Trevise","IT"),
("TSN","Tianjin","CN"),
("TSR","Timisoara","RO"),
("TUF","Tours","FR"),
("TUN","Tunis","TN"),
("TYO","Tokyo","JP"),
("TZA","Belize City","BZ"),
("TZL","Tuzla","BA"),
("UAK","Narssarssuaq","GL"),
("UDR","Udaipur","IN"),
("UET","Quetta","PK"),
("UII","Utila Island","HN"),
("UIO","Quito","EC"),
("UIP","Quimper","FR"),
("UKB","Kobe","JP"),
("UKY","Kyoto","JP"),
("ULN","Oulan Bator","MN"),
("UPG","Ujung Pandang","ID"),
("URC","Urumqi","CN"),
("URO","Rouen","FR"),
("USH","Ushuaia","AR"),
("USM","Koh Samui","TH"),
("UUD","Ulan Ude","RU"),
("UVE","Ouvea","NC"),
("VAN","Van","TR"),
("VAP","Valparaiso","CL"),
("VAR","Varna","BG"),
("VCA","Can Tho","VN"),
("VCE","Venise","IT"),
("VCP","Campinas","BR"),
("VDA","Eilat","IL"),
("VER","Veracruz","MX"),
("VFA","Victoria Falls","ZW"),
("VGO","Vigo","ES"),
("VIE","Vienne","AT"),
("VIT","Vitoria","ES"),
("VKO","Vnoukovo","RU"),
("VLC","Valence","ES"),
("VLI","Port Vila","VU"),
("VLL","Valladolid","ES"),
("VLN","Valencia","VE"),
("VNO","Vilnius","LT"),
("VNS","Varanasi","IN"),
("VRA","Varadero","CU"),
("VRN","Verone","IT"),
("VTE","Vientiane","LA"),
("VVI","Santa Cruz","BO"),
("VVO","Vladivostok","RU"),
("VXE","Sao Vicente","CV"),
("WAS","Washington","US"),
("WAW","Varsovie","PL"),
("WDH","Windhoek","NA"),
("WFI","Fianarantsoa","MG"),
("WGL","Baltra Island","EC"),
("WHF","Wadi Halfa","SD"),
("WLG","Wellington","NZ"),
("WLS","Wallis","WF"),
("WMR","Mananara","MG"),
("WNT","Hierro","ES"),
("WPU","Puerto Williams","CL"),
("WRO","Wroclaw","PL"),
("WVB","Walvis Bay","NA"),
("WVK","Manakara","MG"),
("XLS","Saint Louis","SN"),
("XQP","Quepos","CR"),
("YAO","Yaounde","CM"),
("YBC","Baie-Comeau","CA"),
("YBG","Saguenay","CA"),
("YDA","Dawson","CA"),
("YED","Edmonton","CA"),
("YFC","Fredericton","CA"),
("YGR","Havre aux Maisons","CA"),
("YHZ","Halifax","CA"),
("YOK","Yokohama","JP"),
("YOW","Ottawa","CA"),
("YQB","Quebec","CA"),
("YQM","Moncton","CA"),
("YRQ","Trois-Rivieres","CA"),
("YTO","Toronto","CA"),
("YVA","Moroni","KM"),
("YVR","Vancouver","CA"),
("YWG","Winnipeg","CA"),
("YXY","Whitehorse","CA"),
("YYC","Calgary","CA"),
("ZAD","Zadar","HR"),
("ZAG","Zagreb","HR"),
("ZAM","Zamboanga","PH"),
("ZAO","Cahors","FR"),
("ZAZ","Saragosse","ES"),
("ZGC","Lanzhou","CN"),
("ZIG","Ziguinchor","SN"),
("ZND","Zinder","NE"),
("ZNZ","Zanzibar","TZ"),
("ZPE","Onasbruck","DE"),
("ZRE","Rethymnon","GR"),
("ZRH","Zurich","CH"),
("ZVK","Savannakhet","LA");

