##INSERTION DES DONNÉES DANS LA TABLE tblCompagnieAerienne

USE BD_Aeroport_2018;

INSERT INTO tblCompagnieAerienne VALUES
("AA","American Airlines"),
("AB","Air Berlin"),
("AC","Air Canada"),
("AD","Air Paradise"),
("AE","Mandarin Airlines"),
("AF","Air France"),
("AH","Air Algerie"),
("AI","Air India"),
("AK","Air Asia Sen"),
("AM","Aeromexico Aerovias de Mexico"),
("AO","Australian Airlines"),
("AQ","Aloha Airlines"),
("AR","Aerolineas Argentinas"),
("AS","Alaska Airlines"),
("AT","Royal Air Maroc"),
("AV","Avianca"),
("AX","Trans States Airlines "),
("AY","Finnair Oyj"),
("AZ","Alitalia Linee Aeree Italiane"),
("A2","Cielos del Peru"),
("A3","Aegean Airlines"),
("A4","Southern Winds"),
("A5","HOP! "),
("A6","Asia Pacific Airlines "),
("A8","Benin Golf Air"),
("A9","Georgian Airlines"),
("BA","British Airways"),
("BC","Skymark Airlines"),
("BD","British Midland Airways Ltd."),
("BG","Biman Bangladesh Airlines"),
("BH","Hawkair Aviation Services"),
("BI","Royal Brunei Airlines"),
("BJ","Nouvelair Tunisia"),
("BL","Pacific Airlines"),
("BM","Bayu Indonesia Air"),
("BP","Air Botswana Corp"),
("BQ","Aeromar Airlines"),
("BT","Air Baltic"),
("BU","Braathens groupe SAS"),
("BV","Blue Panorama Airlines"),
("BW"," British West Indian Airways"),
("B2","Belavia"),
("B8","Eritrean Airlines"),
("B9"," Air Bangladesh"),
("CA","Air China Ltd"),
("CE","Nationwide Airlines"),
("CI","China Airlines"),
("CL","Lufthansa CityLine"),
("CM"," Compania Panamena de Aviacion"),
("CO","Continental Airlines"),
("CP","Canadian Airlines International"),
("CR","Corsair "),
("CS","Continental Micronesia"),
("CU","Cubana"),
("CW","Air Marshall Islands"),
("CX","Cathay Pacific Airways"),
("CY","Cyprus Airways"),
("CZ","China Southern Airlines"),
("C6","CanJet"),
("DA","Air Georgia"),
("DB","Brit Air"),
("DG","Eastern Pacific"),
("DJ","Virgin Blue"),
("DL","Delta Air Lines"),
("DM","Maersk Air"),
("DN","Senegal Airlines"),
("DR","Air Mediterranee"),
("DS","EasyJet Switzerland"),
("DT","TAAG Angola Airlines"),
("DU","Hemus Air"),
("DX","Danish Air Transport"),
("D7","Dinar Lineas Aereas"),
("D8","Diamond Sakha Airlines"),
("EA","European Air Express"),
("EC","OpenSkies "),
("EE","Aero Airlines"),
("EG","Japan Asia Airways"),
("EI","Aer Lingus"),
("EK","Emirates"),
("EL","Air Nippon"),
("EO","Hewa Bora Airways"),
("EP","Iran Aseman Airlines"),
("ET","Ethiopian Airlines"),
("EV","Atlantic Southeast Airlines"),
("EY","Etihad Airways"),
("EX","Air Santo Domingo"),
("EZ","Sun Air of Scandinavia"),
("E3","Domodedovo Airlines"),
("E4","Aero Asia"),
("E5","Samara Airlines (Rus.),"),
("FB","Bulgaria Air"),
("FC","Finncomm Airlines"),
("FD","Thai Air Asia"),
("FG","Ariana Afghan Airlines"),
("FI","Icelandair"),
("FJ","Air Pacific"),
("FM","Shanghai Airlines Co. Ltd."),
("FN","Regional Airlines"),
("FP","Freedom Air"),
("FR","Ryanair"),
("FZ","Flydubai"),
("GA","Garuda Indonesia"),
("GC","Gambia International Airlines"),
("GE","Transasia Airways"),
("GF","Gulf Air"),
("GH","Ghana Airways Corp"),
("GJ","Eurofly"),
("GM","Air Slovakia"),
("GN","Air Gabon"),
("GZ","Air Rarotonga"),
("G3","Gol"),
("HA","Hawaiian Airlines"),
("HC","Holidays Czech Airlines"),
("HG","Niki"),
("HH","Islandsflug"),
("HM","Air Seychelles"),
("HP","America West Airlines"),
("HQ","Thomas Cook Airlines Belgium"),
("HU","Hainan Airlines Co. Ltd."),
("HV","Transavia Airlines"),
("HY","Uzbekistan Airways"),
("IB","Iberia Lineas Aereas de Espana"),
("IC","Indian Airlines Limited"),
("IE","Solomon Airlines"),
("IG","Meridiana S.p.A."),
("IH","Falcon Air AB"),
("IK","Imair Airlines"),
("IN","MAT Macedonian Airlines"),
("IR","Iran Air"),
("IY","Yemenia"),
("IZ","Arkia Israeli Airlines"),
("I5","Compagnie Aerienne du Mali"),
("JA","Air Bosna"),
("JJ","TAM Linhas Aereas"),
("JK","Spanair SA"),
("JL","Japan Airlines"),
("JM","Air Jamaica"),
("JP","Adria Airways"),
("JR","Aero California"),
("JS","Air Koryo Korean Airways"),
("JU","Jat Airways"),
("J2","Azerbaijan Airlines Hava Yollary"),
("KA","Dragonair"),
("KB","Druk Air"),
("KC","Air Astana"),
("KE","Korean Air"),
("KL","KLM Royal Dutch Airlines"),
("KM","Air Malta"),
("KP","Asky"),
("KQ","Kenya Airways"),
("KU","Kuwait Airways"),
("K6"," Cambodia Angkor Air"),
("K8","Kaliningradavia"),
("LA","Lan Airlines"),
("LB","Lloyd Aereo Boliviano LAB"),
("LG","Luxair"),
("LH","Deutsche Lufthansa AG"),
("LK","Air Luxor SA"),
("LN","Libyan Arab Airlines"),
("LO","Lot Polish Airlines"),
("LR","Lacsa Lineas Aereas Costarricenses SA"),
("LT","Air Lituanica"),
("LV","Albanian Airlines MAK S.H.P.K."),
("LX","Swiss International Air Lines Ltd"),
("LY","El Al-Israel Airlines"),
("LZ","Balkan Bulgarian Airlines"),
("MA","Malév Hungarian Airline"),
("MC","Air Cairo"),
("MD","Air Madagascar"),
("ME","Middle East Airlines"),
("MH","Malaysia Airlines"),
("MK","Air Mauritius Ltd"),
("MM","SAM"),
("MP","Martinair Holland"),
("MR","Air Mauritanie"),
("MS","Egypt Air"),
("MU","China Eastern Airlines"),
("NE","Sky Europe Airlines"),
("NF","Air Vanuatu"),
("NI","Portugalia Companhia Portuguesa"),
("NQ","Air Japan"),
("NW","Northwest Airlines"),
("NX","Air Macau"),
("NZ","Air New Zealand"),
("N2","Aerolineas Internacionales"),
("OA","Olympic Airlines"),
("OB","Astrahan Airlines"),
("OH","Comair Inc."),
("OK","CSA Czech Airlines"),
("OM","MIAT Mongolian Airlines"),
("ON","Our Airline"),
("OO","SkyWest Airlines"),
("OR","Crimea Air"),
("OS","Austrian Airlines"),
("OU","Croatia Airlines"),
("OV","Estonian Air"),
("OZ","Asiana Airlines"),
("O6","OceanAir Linhas Aereas"),
("PC","Air Fiji Ltd."),
("PF","Palestinian Airlines"),
("PG","Bangkok Airways"),
("PH","Polynesian Airlines"),
("PJ","Air Saint-Pierre"),
("PK","Pakistan International Airlines"),
("PL","Aeroperu"),
("PR","Philippine Airlines"),
("PS","Ukraine International Airlines"),
("PU","Pluna Lineas Aereas Uruguayas"),
("PW","Precision Air"),
("PX","Air Niugini"),
("PY","Surinam Airways"),
("PZ"," TAM Mercosur"),
("P5","AeroRepublica"),
("QF","Qantas Airways"),
("QC","Camair-Co"),
("QM","Air Malawi"),
("QR","Qatar Airways"),
("QV","Lao Aviation"),
("Q3","Zambian Airways"),
("RA","Royal Nepal Airlines Corporation"),
("RB","Syrian Arab Airlines"),
("RD","Alitalia Team"),
("RG","Varig Brasil"),
("RJ","Royal Jordanian"),
("RK","Royal Khmer Airlines"),
("RM","Air Moldova International"),
("R2","Orenburg Airlines"),
("R4","Russia Airline"),
("SA","South African Airways"),
("SB","Aircalin Air Calédonie International"),
("SD","Sudan Airways"),
("SH","AirToulouse/Aeris"),
("SF","Tassili Airlines"),
("SK","Scandinavian Airlines"),
("SN","Sabena"),
("SP","SATA Air Açores"),
("SQ","Singapore Airlines LTD."),
("SR","Swissair"),
("SS"," Corsairfly"),
("SU","Aeroflot Russian Airlines"),
("SV","Saudi Arabian Airlines"),
("SW","Air Namibia"),
("SZ","China Southwest"),
("S4","SATA Internacional"),
("S7","Siberia Airlines"),
("TA","Taca International Airlines"),
("TB","Air Tanzania Co. Ltd."),
("TG","Thai Airways International"),
("TK","Turkish Airlines"),
("TM","Linhas Aereas de Moçambique"),
("TN","Air Tahiti Nui"),
("TP","TAP Portugal"),
("TR","Tiger Airways"),
("TS","Air Transat"),
("TT","Air Lithuania"),
("TU","Tunisair"),
("TV","Virgin Express"),
("TY","Air Calédonie"),
("TZ","ATA Airlines"),
("T5","Turkmenistan Airlines"),
("UA","United Airlines Inc."),
("UB","Myanmar Airways"),
("UI","Eurocypria Airlines"),
("UL","SriLankan Airlines"),
("UM","Air Zimbabwe"),
("US","US Airways"),
("UU","Air Austral"),
("UW","Universal Airlines"),
("UY","Cameroon Airlines"),
("U2","EasyJet"),
("VD","Swedjet Airways"),
("VH","Aeropostal Alas de Venezuela CA"),
("VJ","Royal Air Cambodge"),
("VN","Vietnam Airlines"),
("VO","Tyrolean Airways"),
("VR","TACV Cabo Verde Airlines"),
("VS","Virgin Atlantic Airways Ltd."),
("VT","Air Tahiti"),
("VU","Air Ivoire"),
("VV","Aerosvit"),
("WB","Rwandair Express"),
("WG","Sunwing Airlines"),
("WM","Windward Islands Airways"),
("WN","Southwest Airlines"),
("WS","WestJet"),
("WY","Oman Air"),
("WX","Cityjet"),
("W5","Mahan Airlines"),
("WJ","Air Labrador"),
("XC","Air Caribbean"),
("XF","Vladivostok Avia JSC"),
("X5","Afrique Airlines"),
("YB","South African Express"),
("YD","Mauritania Airways"),
("YH","Air Nunavut Ltd."),
("YM","Montenegro Airlines"),
("YT","Air Togo"),
("YV","Mesa Airlines"),
("YX","Midwest Airlines"),
("ZC","Royal Swazi National Airways Corp."),
("ZE","Lineas Aereas Azteca"),
("ZS","Azzurra Air"),
("Z9","Aero Zambia"),
("2J","Air Burkina"),
("2P","Air Philippines"),
("3H","Air Inuit"),
("3O","Air Arabia Maroc"),
("3R","Air Moldova International"),
("4A","Air Kiribati"),
("4G","Shenzhen Airlines"),
("4Z","South African Airlink"),
("5P","SkyEurope Airlines"),
("6G","Air Wales"),
("6T","Air Mandalay"),
("6U","Air Ukraine"),
("6W","Saravia"),
("7I","Insel Air"),
("7J","Tajikistan Airlines"),
("8R","Sol Lineas Aereas"),
("8U","Afriqiyah Airways"),
("9D","Toumai Air Tchad"),
("9U","Air Moldova");