##INSERTION DES DONNÉES DANS LA TABLE tblAeroport

USE BD_Aeroport_2018;

INSERT INTO tblAeroport VALUES
("AAE","Aeroport d'Annaba","213(0),38520134",1,"AAE"),
("MST","Aeroport Maastricht Aachen","31433589898",1,"MST"),
("AAK","Aeroport d'Aranuka","N/D",13,"BUA"),
("AAL","Aeroport d'Aalborg","4598171144",1,"AAL"),
("AAR","Aeroport d'Arhus","4525449746",1,"AAR"),
("AAN","Aeroport international Al Ain","971(2),5055000",4,"ALI"),
("ABJ","Aeroport international d'Abidjan","N/D",0,"ABJ"),
("ABQ","Aeroport international d'Albuquerque","N/D",-7,"ABQ"),
("ABS","Aeroport d'Abou Simbel","N/D",2,"ABS"),
("ABV","Aeroport international Nnamdi Azikiwe","N/D",1,"ABV"),
("ABZ","Aeroport d'Aberdeen, Dyce","N/D",0,"ABZ"),
("ACA","Aeroport international general Juan N. Alvarez","N/D",-6,"ACA"),
("ACC","Aeroport international de Kotoka","N/D",0,"ACC"),
("ACE","Aeroport d'Arrecife, ile de Lanzarote","N/D",0,"ACE"),
("ADD","Aeroport international de Bole","N/D",3,"ADD"),
("ADE","Aeroport Aden International","N/D",3,"ADE"),
("ADL","Aeroport international d'Adelaide","N/D",10,"ADL"),
("ADZ","Aeroport international Gustavo Rojas Pinilla","N/D",-5,"ADZ"),
("AGA","Aeroport Agadir-Al Massira","N/D",0,"AGA"),
("AGP","Aeroport de Malaga","N/D",1,"AGP"),
("AGR","Aeroport d'Agra","N/D",5,"AGR"),
("AHO","Aeroport Fertilia","N/D",1,"AHO"),
("AJA","Aeroport Ajaccio-Napoleon Bonaparte","N/D",1,"AJA"),
("AJN","Aeroport d'Ouani","N/D",Null,"AJN"),
("AJY","Aeroport Mano Dayak","N/D",Null,"AJY"),
("AKL","Aeroport d'Auckland","N/D",13,"AKL"),
("ALA","Aeroport International d'Almaty","N/D",Null,"ALA"),
("ALC","Aeroport d'Alicante","N/D",1,"ALC"),
("ALG","Aeroport d'Alger-Houari Boumediene","N/D",1,"ALG"),
("ALP","Aeroport International d'Alep","N/D",Null,"ALP"),
("ALY","Aeroport d'Alexandrie","N/D",2,"ALY"),
("AMD","Aeroport d'Ahmadabad","N/D",5,"AMD"),
("AMI","Aeroport Selaparang","N/D",Null,"AMI"),
("AMM","Aeroport international Queen Alia","N/D",Null,"AMM"),
("AMS","Aeroport d'Amsterdam-Schiphol","N/D",1,"AMS"),
("ANC","Aeroport international d'Anchorage Ted Stevens","N/D",Null,"ANC"),
("ANE","Aeroport d'Angers-Marce","N/D",Null,"ANE"),
("ANF","Aeroport Cerro Moreno","N/D",Null,"ANF"),
("ANG","Aeroport international Angouleme-Cognac","N/D",Null,"ANG"),
("ANK","Aeroport d'Ankara-Esenboga","N/D",2,"ANK"),
("ANU","Aeroport de Saint John's","N/D",Null,"ANU"),
("APW","Aeroport Faleolo","N/D",Null,"APW"),
("AQJ","Aeroport d'Aqaba","N/D",Null,"AQJ"),
("AQP","Aeroport Rodriguez Ballon","N/D",-5,"AQP"),
("ARK","Aeroport d'Arusha","N/D",Null,"ARK"),
("ASB","Aeroport d'Achgabat","N/D",Null,"ASB"),
("ASD","Aeroport International Andros","N/D",Null,"ASD"),
("ASM","Aeroport international d'Asmara","N/D",Null,"ASM"),
("ASP","Aeroport d'Alice Springs","N/D",9,"ASP"),
("ASU","Aeroport international Silvio Pettirossi","N/D",Null,"ASU"),
("ASW","Aeroport d'Assouan","N/D",Null,"ASW"),
("ATH","Aeroport International Eleftherios-Venizelos","N/D",2,"ATH"),
("ATL","Aeroport international Hartsfield-Jackson","N/D",-5,"ATL"),
("ATQ","Aeroport international de Raja Sansi","N/D",Null,"ATQ"),
("ATR","Aeroport international d'Atar","N/D",Null,"ATR"),
("AUA","Aeroport international Reine Beatrix","N/D",Null,"AUA"),
("AUF","Aeroport d'Auxerre-Branches","N/D",Null,"AUF"),
("AUH","Aeroport international d'Abou Dabi","N/D",Null,"AUH"),
("AUR","Aeroport d'Aurillac","N/D",Null,"AUR"),
("AVN","Aeroport d'Avignon-Caumont","N/D",Null,"AVN"),
("AXA","Aeroport de Wallblake","N/D",Null,"AXA"),
("AYQ","Aeroport Ayers Rock","N/D",Null,"AYQ"),
("AYT","Aeroport d'Antalya","N/D",Null,"AYT"),
("BAH","Aeroport international de Bahrein","N/D",Null,"BAH"),
("BAK","Aeroport international Heydar Aliyev","N/D",Null,"BAK"),
("BBK","Aeroport de Kasane","N/D",Null,"BBK"),
("BBQ","Aeroport de Codrington","N/D",Null,"BBQ"),
("BBR","Aeroport de Baillif","N/D",Null,"BBR"),
("BBZ","Aeroport de Zambezi","N/D",Null,"BBZ"),
("BCN","Aeroport international El Prat","N/D",1,"BCN"),
("BDA","Aeroport de Kindley Field","N/D",Null,"BDA"),
("BDS","Aeroport Papola Casale","N/D",1,"BDS"),
("BEG","Aeroport Nikola-Tesla","N/D",Null,"BEG"),
("BEL","Aeroport de Vale de Caes","N/D",Null,"BEL"),
("BEN","Aeroport de Benina","N/D",Null,"BEN"),
("BER","Aeroport international Brandenburg-Willy Brandt","N/D",1,"BER"),
("BES","Aeroport international de Brest Bretagne-Guipavas","N/D",Null,"BES"),
("BEW","Aeroport de Beira","N/D",2,"BEW"),
("BEY","Aeroport international Rafic Hariri","N/D",Null,"BEY"),
("BFS","Aeroport international de Belfast","N/D",Null,"BFS"),
("BGF","Aeroport international M'Poko","N/D",Null,"BGF"),
("BGI","Aeroport international Grantley-Adams","N/D",Null,"BGI"),
("BGO","Aeroport de Bergen","N/D",Null,"BGO"),
("BGW","Aeroport international de Bagdad","N/D",3,"BGW"),
("BGY","Aeroport de Bergame - Orio al serio","N/D",1,"BGY"),
("BGZ","Aeroport de Braga","N/D",0,"BGZ"),
("BHK","Aeroport de Boukhara","N/D",Null,"BHK"),
("BHX","Aeroport international de Birmingham","N/D",Null,"BHX"),
("BHZ","Aeroport Confins-Belo Horizonte","N/D",-2,"BHZ"),
("BIA","Aeroport de Bastia Poretta","N/D",1,"BIA"),
("BIO","Aeroport international de Bilbao","N/D",1,"BIO"),
("BIQ","Aeroport de Biarritz-Anglet-Bayonne","N/D",Null,"BIQ"),
("BJA","Aeroport de Bejaia-Soummam-Abane Ramdane","N/D",Null,"BJA"),
("BJC","Aeroport Jeffco Denver/Broomfield","N/D",-7,"BJC"),
("BJL","Aeroport international de Banjul","N/D",Null,"BJL"),
("BJM","Aeroport international de Bujumbura","N/D",Null,"BJM"),
("BKI","Aeroport international de Kota Kinabalu","N/D",Null,"BKI"),
("BKK","Aeroport international de Bangkok","N/D",7,"BKK"),
("BKL","Aeroport de Burke Lakefront","N/D",-5,"BKL"),
("BKO","Aeroport international de Bamako-Senou","N/D",Null,"BKO"),
("BLA","Aeroport Jose A. Anzoategui","N/D",Null,"BLA"),
("BLL","Aeroport de Billund","N/D",Null,"BLL"),
("BLQ","Aeroport de Borgo Panigale","N/D",1,"BLQ"),
("BLZ","Aeroport International Chileka","N/D",Null,"BLZ"),
("BNE","Aeroport international de Brisbane","N/D",10,"BNE"),
("BNJ","Aeroport Bonn-Hangelar","N/D",Null,"BNJ"),
("BOB","Aeroport de Bora Bora","N/D",Null,"BOB"),
("BOD","Aeroport de Bordeaux-Merignac","N/D",Null,"BOD"),
("BOG","Aeroport de Bogota-El Dorado","N/D",-5,"BOG"),
("BOH","Aeroport de Bournemouth","N/D",Null,"BOH"),
("BOJ","Aeroport de Bourgas","N/D",Null,"BOJ"),
("BOM","Aeroport international de Bombay","N/D",5,"BOM"),
("BON","Aeroport international Flamingo","N/D",Null,"BON"),
("BOO","Aeroport de Bodo","N/D",Null,"BOO"),
("BOS","Aeroport international Logan","N/D",-5,"BOS"),
("BQU","Aeroport de Bequia","N/D",Null,"BQU"),
("BRC","Aeroport de San Carlos de Bariloche","N/D",Null,"BRC"),
("BRE","Aeroport de Breme","N/D",Null,"BRE"),
("BRI","Aeroport Palese Macchie","N/D",1,"BRI"),
("BRN","Aeroport international Berne-Belp","N/D",Null,"BRN"),
("BRQ","Aeroport de Brno-Turany","N/D",Null,"BRQ"),
("BRS","Aeroport de Bristol-Lulsgate","N/D",Null,"BRS"),
("BRU","Aeroport de Bruxelles","N/D","1","BRU"),
("BRX","Aeroport international Maria-Montez","N/D",Null,"BRX"),
("BSB","Aeroport int. Presidente Juscelino Kubitschek","N/D",Null,"BSB"),
("BSG","Aeroport de Bata","N/D",Null,"BSG"),
("BSK","Aeroport Mohamed Khider","N/D",Null,"BSK"),
("BSL","Aeroport international Basel-Mulhouse-Freiburg","N/D",Null,"BSL"),
("BTS","Aeroport M.R.Stefanik","N/D",Null,"BTS"),
("BUD","Aeroport international de Budapest-Ferihegy","N/D",Null,"BUD"),
("BUE","Aeroport de Buenos Aires","N/D",-3,"BUE"),
("BUH","Aeroport de Bucarest","N/D",Null,"BUH"),
("BVA","Aeroport de Paris Beauvais Tille","N/D",Null,"BVA"),
("BVB","Aeroport de Boa Vista","N/D",Null,"BVB"),
("BVC","Aeroport de Rabil","N/D",Null,"BVC"),
("BVE","Aeroport de Brive-Vallee de la Dordogne","N/D",Null,"BVE"),
("BWI","Aeroport international Thurgood Marshall","N/D",-5,"BWI"),
("BWN","Aeroport international de Bandar Seri Begawan","N/D",Null,"BWN"),
("BZE","Aeroport international Philip S. W. Goldson","N/D",Null,"BZE"),
("BZR","Aeroport de Beziers-Cap d'Agde en Languedoc","N/D",Null,"BZR"),
("CAG","Aeroport de Cagliari-Elmas","N/D",1,"CAG"),
("CAI","Aeroport international du Caire","N/D",2,"CAI"),
("CAN","Aeroport de Baiyun-Canton","N/D",8,"CAN"),
("CAP","Aeroport international de Cap-Haïtien","N/D",Null,"CAP"),
("CAS","Aeroport de Anfa","N/D",0,"CAS"),
("CAY","Aeroport international Felix eboue","N/D",Null,"CAY"),
("CBR","Aeroport de Canberra","N/D",11,"CBR"),
("CCC","Aeroport de Cayo Coco","N/D",Null,"CCC"),
("CCE","Aeroport regional de l'Esperance-Grand Case","N/D",Null,"CCE"),
("CCF","Aeroport de Carcassonne Salvaza","N/D",Null,"CCF"),
("CCS","Aeroport international Maiquetia-Simon Bolivar","N/D",-4,"CCS"),
("CCU","Aeroport international Netaji Subhash Chandra Bose","N/D",5,"CCU"),
("CDG","Aeroport Charles-de-Gaulle","N/D",1,"PAR"),
("CEB","Aeroport international de Mactan-Cebu","N/D",8,"CEB"),
("CEI","Aeroport international de Chiang Rai","N/D",Null,"CEI"),
("CEQ","Aeroport de Cannes-Mandelieu","N/D",Null,"CEQ"),
("CER","Aeroport de Cherbourg-Maupertus","N/D",Null,"CER"),
("CFE","Aeroport de Clermont-Ferrand Auvergne","N/D",Null,"CFE"),
("CFG","Aeroport de Cienfuegos","N/D",Null,"CFG"),
("CFR","Aeroport de Caen-Carpiquet","N/D",Null,"CFR"),
("CGN","Aeroport Konrad Adenauer","N/D",1,"CGN"),
("CGO","Aeroport de Zhengzhou","N/D",Null,"CGO"),
("CGP","Aeroport international Shah Amanat","N/D",Null,"CGP"),
("CGT","Aeroport de Chinguetti","N/D",Null,"CGT"),
("CHC","Aeroport international de Christchurch","N/D",Null,"CHC"),
("CHH","Aeroport de Chachapoyas","N/D",-5,"CHH"),
("CHR","Aeroport de Chateauroux-Centre","N/D",Null,"CHR"),
("CHS","Aeroport international de Charleston","N/D",Null,"CHS"),
("CMB","Aeroport international Bandaranaike","N/D",Null,"CMB"),
("CND","Aeroport international Mihail Kogalniceanu","N/D",Null,"CND"),
("CNS","Aeroport international de Cairns","N/D",10,"CNS"),
("COO","Aeroport international de Cotonou","N/D",Null,"COO"),
("CPE","Aeroport international Alberto Acuna Ongay","N/D",Null,"CPE"),
("CPH","Aeroport de Copenhague","N/D",Null,"CPH"),
("CRK","Aeroport international de Diosdado Macapagal","N/D",8,"CRK"),
("CRL","Aeroport de Charleroi Bruxelles-Sud-Gosselies","N/D",Null,"CRL"),
("CTA","Aeroport de Catane-Fontanarossa","N/D",1,"CTA"),
("CTG","Aeroport international Rafael Nunez","N/D",-5,"CTG"),
("CTU","Aeroport de Chengdu","N/D",8,"CTU"),
("CUE","Aeroport Mariscal La Mar","N/D",Null,"CUE"),
("CUK","Aeroport de Caye Caulker","N/D",Null,"CUK"),
("CUN","Aeroport international de Cancun","N/D",Null,"CUN"),
("CUR","Aeroport Hato","N/D",Null,"CUR"),
("CUZ","Aeroport international Alejandro Velasco Astete","N/D",-5,"CUZ"),
("CWL","Aeroport international de Cardiff (Rhoose),","N/D",Null,"CWL"),
("CZL","Aeroport de Constantine-Mohamed Boudiaf","N/D",Null,"CZL"),
("CZM","Aeroport de Cozumel","N/D",Null,"CZM"),
("CZW","Aeroport de Czestochowa","N/D",Null,"CZW"),
("DAC","Aeroport international Shah Jalal","N/D",6,"DAC"),
("DAD","Aeroport de Da Nang","N/D",Null,"DAD"),
("DAL","Aeroport de Dallas Love Field","N/D",-6,"DAL"),
("DAM","Aeroport international de Damas","N/D",Null,"DAM"),
("DAR","Aeroport international Julius Nyerere","N/D",Null,"DAR"),
("DBV","Aeroport de Dubrovnik","N/D",Null,"DBV"),
("DDM","Aeroport de Dodoima","N/D",Null,"DDM"),
("DEL","Aeroport international Indira Gandhi","N/D",5,"DEL"),
("DEN","Aeroport international Stapleton","N/D",-7,"DEN"),
("DET","Aeroport de Detroit","N/D",-5,"DET"),
("DFW","Aeroport international de Dallas/Fort Worth","N/D",-6,"DFW"),
("DHM","Aeroport de Dharamsala","N/D",Null,"DHM"),
("DIJ","Aeroport de Dijon Bourgogne-Longvic","N/D",Null,"DIJ"),
("DIL","Aeroport international de Dili","N/D",Null,"DIL"),
("DIR","Aeroport international d'Aba Tenna Dejazmach Yilma","N/D",Null,"DIR"),
("DJE","Aeroport international de Djerba-Zarzis","N/D",Null,"DJE"),
("DJG","Aeroport Inedbirene de Djanet","N/D",Null,"DJG"),
("DKR","Aeroport international Leopold Sedar Senghor","N/D",Null,"DKR"),
("DLA","Aeroport international de Douala","N/D",Null,"DLA"),
("DME","Aeroport international Domodedovo","N/D",Null,"MOW"),
("DNK","Aeroport de Dnipropetrovs'k","N/D",Null,"DNK"),
("DNR","Aeroport de Dinard/Pleurtuit (St. Malo),","N/D",Null,"DNR"),
("DOH","Aeroport de Doha","N/D",Null,"DOH"),
("DOL","Aeroport de Deauville (Saint Gatien),","N/D",Null,"DOL"),
("DPS","Aeroport international de Denpasar","N/D",Null,"DPS"),
("DRS","Aeroport de Dresde","N/D",Null,"DRS"),
("DRW","Aeroport international de Darwin","N/D",9,"DRW"),
("DSA","Aeroport international de Doncaster Sheffield","N/D",Null,"DSA"),
("DSD","Aeroport de La Desirade","N/D",Null,"DSD"),
("DTM","Aeroport de Dortmund","N/D",Null,"DTM"),
("DUB","Aeroport international de Dublin","N/D",0,"DUB"),
("DUR","Aeroport International de Durban","N/D",Null,"DUR"),
("DUS","Aeroport de Dusseldorf (Rhein-Ruhr),","N/D",1,"DUS"),
("DXB","Aeroport international de Dubai","N/D",4,"DXB"),
("DYU","Aeroport International de Douchanbe","N/D",Null,"DYU"),
("DZA","Aeroport de Dzaoudzi-Pamandzi","N/D",Null,"DZA"),
("EAM","Aeroport de Nejran","N/D",Null,"EAM"),
("EAS","Aeroport de San Sebastian","N/D",Null,"EAS"),
("EBB","Aeroport international d'Entebbe","N/D",Null,"EBB"),
("EBU","Aeroport de Saint-Etienne-Boutheon","N/D",Null,"EBU"),
("ECN","Aeroport international Ercan","N/D",Null,"NIC"),
("EDI","Aeroport d'Edimbourg","N/D",Null,"EDI"),
("EIN","Aeroport d'Eindhoven","N/D",Null,"EIN"),
("ELP","Aeroport international d'El Paso","N/D",Null,"ELP"),
("ELS","Aeroport d'East London","N/D",Null,"ELS"),
("EMA","Aeroport d'East Midlands (Derby),","N/D",Null,"EMA"),
("ENC","Aeroport de Nancy-Essey","N/D",Null,"ENC"),
("EPS","Aeroport international Arroyo Barril","N/D",Null,"EPS"),
("ERI","Aeroport international d'Erie","N/D",-5,"ERI"),
("ESB","Aeroport international Esenboga","N/D",Null,"ANK"),
("EVN","Aeroport d'Erevan","N/D",Null,"EVN"),
("EWR","Aeroport international de Newark","N/D",-5,"EWR"),
("EXT","Aeroport d'Exeter","N/D",Null,"EXT"),
("EYW","Aeroport international de Key West","N/D",Null,"EYW"),
("FAI","Aeroport international de Fairbanks","N/D",Null,"FAI"),
("FAO","Aeroport de Faro","N/D",0,"FAO"),
("FAR","Aeroport international Hector","N/D",Null,"FAR"),
("FBM","Aeroport international de Lubumbashi","N/D",Null,"FBM"),
("FBU","Aeroport d'Oslo","N/D",Null,"OSL"),
("FCO","Aeroport Leonardo da Vinci/Fiumicino","N/D",1,"ROM"),
("FDF","Aeroport de Fort-de-France","N/D",Null,"FDF"),
("FEZ","Aeroport de Fes","N/D",Null,"FEZ"),
("FIH","Aeroport de Kinshasa","N/D",1,"FIH"),
("FJR","Aeroport international de Fujairah","N/D",1,"FIH"),
("FLL","Aeroport international de Fort Lauderdale","N/D",-5,"FLL"),
("FLR","Aeroport de Florence","N/D",1,"FLR"),
("FNA","Aeroport de Freetown","N/D",Null,"FNA"),
("FNI","Aeroport de Nimes/Arles-Camargue (Garons),","N/D",Null,"FNI"),
("FNJ","Aeroport de Pyongyang-Sunan","N/D",Null,"FNJ"),
("FNT","Aeroport international de Bishop","N/D",Null,"FNT"),
("FOR","Aeroport international de Fortaleza","N/D",Null,"FOR"),
("FPO","Aeroport international de Freeport","N/D",Null,"FPO"),
("FRA","Aeroport international de Francfort","N/D",1,"FRA"),
("FRS","Aeroport de Flores","N/D",Null,"FRS"),
("FRU","Aeroport international de Manas","N/D",Null,"FRU"),
("FTU","Aeroport de Fort Dauphin","N/D",Null,"FTU"),
("FUE","Aeroport de Fuerteventura","N/D",1,"FUE"),
("FUK","Aeroport de Fukuoka","N/D",9,"FUK"),
("FWA","Aeroport international de Fort Wayne","N/D",Null,"FWA"),
("GAE","Aeroport de Gabes-Matmata","N/D",Null,"GAE"),
("GAF","Aeroport international de Gafsa-Ksar","N/D",Null,"GAF"),
("GAN","Aeroport international de Gan","N/D",Null,"GAN"),
("GAQ","Aeroport de Gao","N/D",Null,"GAQ"),
("GBE","Aeroport international Sir Seretse Khama","N/D",Null,"GBE"),
("GCI","Aeroport de Guernesey","N/D",Null,"GCI"),
("GCM","Aeroport international Owen Roberts","N/D",Null,"GCM"),
("GDL","Aeroport Miguel Hidalgo y Costilla","N/D",-6,"GDL"),
("GDN","Aeroport Rebiechowo","N/D",Null,"GDN"),
("GDT","Aeroport de Grand Turk","N/D",Null,"GDT"),
("GEA","Aeroport de Magenta","N/D",Null,"NOU"),
("GEO","Aeroport Timehri","N/D",Null,"GEO"),
("GIB","Aeroport North Front","N/D",Null,"GIB"),
("GLA","Aeroport international de Glasgow","N/D",Null,"GLA"),
("GNB","Aeroport International de Grenoble-Isere","N/D",Null,"GNB"),
("GND","Aeroport de Pointe Salines","N/D",Null,"GND"),
("GOI","Aeroport de Goa","N/D",Null,"GOI"),
("GOQ","Aeroport de Golmud","N/D",Null,"GOQ"),
("GOT","Aeroport Landvetter","N/D",Null,"GOT"),
("GOU","Aeroport de Garoua","N/D",Null,"GOU"),
("GPS","Aeroport Seymour","N/D",Null,"GPS"),
("GRO","Aeroport de Gerone-Costa Brava","N/D",1,"GRO"),
("GRW","Aeroport de Graciosa-Acores","N/D",-1,"GRW"),
("GRZ","Aeroport Thalerhof","N/D",Null,"GRZ"),
("GUA","Aeroport international La Aurora","N/D",Null,"GUA"),
("GUM","Aeroport international Antonio-B.-Won-Pat","N/D",Null,"GUM"),
("GVA","Aeroport international de Geneve","N/D",Null,"GVA"),
("GWY","Aeroport Galway-Cammore","N/D",Null,"GWY"),
("GYE","Aeroport international Jose Joaquin de Olmedo","N/D",Null,"GYE"),
("GZA","Aeroport international Yasser Arafat","N/D",Null,"GZA"),
("GZM","Aeroport de Gozo","N/D",Null,"GZM"),
("HAH","Aeroport international Prince Said Ibrahim","N/D",Null,"HAH"),
("HAJ","Aeroport Langenhagen","N/D",Null,"HAJ"),
("HAM","Aeroport Fuhlsbuttel","N/D",Null,"HAM"),
("HAN","Aeroport Noi-Bai","N/D",7,"HAN"),
("HAV","Aeroport International Jose Marti","N/D",Null,"HAV"),
("HBA","Aeroport de Hobart","N/D",11,"HBA"),
("HEL","Aeroport Vantaa","N/D",Null,"HEL"),
("HER","Aeroport Heraklion Nikos-Kazantzakis","N/D",Null,"HER"),
("HFA","Aeroport d'Haifa","N/D",2,"HFA"),
("HIR","Aeroport Henderson","N/D",Null,"HIR"),
("HIX","Aeroport d'Hiva Oa-Iles Marquises","N/D",Null,"HIX"),
("HKG","Aeroport international de Hong Kong","N/D",8,"HKG"),
("HKT","Aeroport international de Phuket","N/D",Null,"HKT"),
("HNL","Aeroport international d'Honolulu","N/D",Null,"HNL"),
("HOG","Aeroport d'Holguin","N/D",Null,"HOG"),
("HOU","Aeroport William P. Hobby","N/D",-6,"HOU"),
("HRE","Aeroport international d'Harare","N/D",Null,"HRE"),
("HUY","Aeroport international de Humberside","N/D",Null,"HUY"),
("HYD","Aeroport international de Hyderabad","N/D",5,"HYD"),
("IAD","Aeroport international Washington Dulles","N/D",-5,"WAS"),
("IEV","Aeroport Zhulyany","N/D",Null,"IEV"),
("IFN","Aeroport international d'Ispahan","N/D",Null,"IFN"),
("IGR","Aeroport Cataratas del Iguazu","N/D",Null,"IGR"),
("IKA","Aeroport international Imam Khomeini","N/D",Null,"THR"),
("IKT","Aeroport d'Irkutsk","N/D",Null,"IKT"),
("ILP","Aeroport de Ile des Pins","N/D",Null,"ILP"),
("IND","Aeroport international d'Indianapolis","N/D",Null,"IND"),
("INN","Aeroport Kranebitten","N/D",Null,"INN"),
("INU","Aeroport international de Nauru","N/D",Null,"INU"),
("IST","Aeroport international Ataturk/Yesilkov","N/D",2,"IST"),
("ITM","Aeroport international d'Osaka","N/D",9,"OSA"),
("IZM","Aeroport A. Menderes","N/D",Null,"IZM"),
("JAX","Aeroport international de Jacksonville","N/D",-5,"JAX"),
("JFK","Aeroport John F. Kennedy","N/D",-5,"NYC"),
("JHB","Aeroport international de Senai","N/D",Null,"JHB"),
("JIB","Aeroport international Ambouli","N/D",Null,"JIB"),
("JKT","Aeroport de Kemayoran","N/D",7,"JKT"),
("JMK","Aeroport de Mykonos","N/D",Null,"JMK"),
("JNB","Aeroport international Jan Smuts","N/D",Null,"JNB"),
("JOG","Aeroport international de Yogyakarta","N/D",Null,"JOG"),
("JRO","Aeroport international du Kilimandjaro","N/D",Null,"JRO"),
("JUL","Aeroport international Inca Manco Capac","N/D",-5,"JUL"),
("KBL","Aeroport international de Kaboul","N/D",Null,"KBL"),
("KCH","Aeroport international de Kuching","N/D",Null,"KCH"),
("KDH","Aeroport international de Kandahar","N/D",Null,"KDH"),
("KEF","Aeroport international Keflavik","N/D",Null,"REK"),
("KGL","Aeroport Kanombe","N/D",Null,"KGL"),
("KHH","Aeroport international de Kaohsiung","N/D",Null,"KHH"),
("KHI","Aeroport international Jinnah","N/D",5,"KHI"),
("KIN","Aeroport international Norman Manley","N/D",Null,"KIN"),
("KIV","Aeroport de Kishinev","N/D",Null,"KIV"),
("KNO","Aeroport international de Kuala Namu","N/D",Null,"KNO"),
("KRK","Aeroport de Balice","N/D",Null,"KRK"),
("KRT","Aeroport international de Khartoum","N/D",Null,"KRT"),
("KTM","Aeroport international Tribhuvan","N/D",Null,"KTM"),
("KUL","Aeroport international de Kuala Lumpur","N/D",8,"KUL"),
("KWI","Aeroport international de Koweit","N/D",Null,"KWI"),
("LAD","Aeroport Quatro de Fevereiro de Luanda","N/D",Null,"LAD"),
("LAX","Aeroport international de Los Angeles","N/D",-8,"LAX"),
("LBA","Aeroport de Leeds-Bradford","N/D",Null,"LBA"),
("LBV","Aeroport international Leon Mba","N/D",Null,"LBV"),
("LCA","Aeroport International de Larnaca","N/D",Null,"LCA"),
("LED","Aeroport international Pulkovo","N/D",Null,"LED"),
("LFW","Aeroport international de Lome-Tokoin","N/D",Null,"LFW"),
("LGA","Aeroport La Guardia","N/D",Null,"NYC"),
("LGG","Aeroport Bierset","N/D",Null,"LGG"),
("LGK","Aeroport international de Langkawi","N/D",Null,"LGK"),
("LGW","Aeroport Gatwick","N/D",Null,"LON"),
("LHE","Aeroport international Allama Iqbal","N/D",5,"LHE"),
("LHR","Aeroport Heathrow","N/D",0,"LON"),
("LIL","Aeroport de Lille Lesquin","N/D",Null,"LIL"),
("LIM","Aeroport international Jorge Chavez","N/D",-5,"LIM"),
("LIS","Aeroport Portela de Sacavem","N/D",0,"LIS"),
("LJU","Aeroport Joze Pucnik de Ljubljana","N/D",Null,"LJU"),
("LLW","Aeroport international Kamuzu","N/D",Null,"LLW"),
("LOS","Aeroport international Murtala Muhammed","N/D",1,"LOS"),
("LPA","Aeroport de Las Palmas/Gran Canaria","N/D",0,"LPA"),
("LPB","Aeroport international El Alto","N/D",Null,"LPB"),
("LPL","Aeroport John Lennon","N/D",Null,"LPL"),
("LPQ","Aeroport de Luang Prabang","N/D",Null,"LPQ"),
("LRM","Aeroport international Casa de Campo","N/D",Null,"LRM"),
("LTN","Aeroport Luton","N/D",Null,"LON"),
("LUG","Aeroport Agno","N/D",Null,"LUG"),
("LUN","Aeroport international de Lusaka","N/D",Null,"LUN"),
("LUX","Aeroport Findel","N/D",Null,"LUX"),
("LXA","Aeroport de Lhassa Gonggar","N/D",Null,"LXA"),
("LXR","Aeroport de Louxor","N/D",Null,"LXR"),
("LYR","Aeroport Longyearbyen","N/D",Null,"LYR"),
("MAA","Aeroport Chennai","N/D",5,"MAA"),
("MAD","Aeroport Barajas","N/D",1,"MAD"),
("MAN","Aeroport de Manchester","N/D",0,"MAN"),
("MAO","Aeroport Eduardo Gomes","N/D",Null,"MAO"),
("MBA","Aeroport international Moi","N/D",Null,"MBA"),
("MBJ","Aeroport international Donald Sangster","N/D",Null,"MBJ"),
("MCT","Aeroport de Mascate","N/D",Null,"MCT"),
("MCZ","Aeroport international Zumbi-dos-Palmares ","N/D",Null,"MCZ"),
("MDE","Aeroport international Jose Maria Cordova","N/D",-5,"MDE"),
("MDL","Aeroport international de Mandalay","N/D",Null,"MDL"),
("MED","Aeroport int. Prince Mohammad Bin Abdulaziz","N/D",Null,"MED"),
("MEL","Aeroport de Melbourne","N/D",11,"MEL"),
("MEM","Aeroport international de Memphis","N/D",Null,"MEM"),
("MEX","Aeroport international de Mexico","N/D",-6,"MEX"),
("MFM","Aeroport international de Macao","N/D",Null,"MFM"),
("MGA","Aeroport international Augusto Cesar Sandino","N/D",Null,"MGA"),
("MGQ","Aeroport international de Mogadiscio ","N/D",Null,"MGQ"),
("MIA","Aeroport international de Miami","N/D",-5,"MIA"),
("MIL","Aeroport de Milan","N/D",1,"MIL"),
("MIR","Aeroport international de Monastir Habib-Bourguiba","N/D",Null,"MIR"),
("MKE","Aeroport international General Mitchell","N/D",Null,"MKE"),
("MLA","Aeroport international de Malte","N/D",Null,"MLA"),
("MLE","Aeroport international de Male","N/D",Null,"MLE"),
("MLW","Aeroport Spriggs Payne","N/D",Null,"MLW"),
("MMX","Aeroport de Malmo","N/D",Null,"MMX"),
("MMK","Aeroport de Mourmansk","N/D",Null,"MMK"),
("MMO","Aeroport de Maio","N/D",Null,"MMO"),
("MNL","Aeroport international Ninoy Aquino","N/D",8,"MNL"),
("MOW","Aeroport de Moscou","N/D",3,"MOW"),
("MPM","Aeroport international de Maputo","N/D",2,"MPM"),
("MPN","Aeroport de Mount Pleasant","N/D",Null,"MPN"),
("MRD","Aeroport de Merida","N/D",Null,"MRD"),
("MRS","Aeroport de Marseille","N/D",Null,"MRS"),
("MRU","Aeroport Sir Seewoosagur Ramgoolam","N/D",Null,"MRU"),
("MRX","Aeroport de Margarita Island","N/D",Null,"MRX"),
("MSP","Aeroport de Minneapolis/St. Paul","N/D",Null,"MSP"),
("MSQ","Aeroport International de Minsk","N/D",Null,"MSQ"),
("MSU","Aeroport international Moshoeshoe","N/D",Null,"MSU"),
("MSW","Aeroport de Massawa","N/D",Null,"MSW"),
("MSY","Aeroport international Louis Armstrong","N/D",Null,"NEW"),
("MTY","Aeroport international General Mariano Escobedo","N/D",-6,"MTY"),
("MUB","Aeroport de Maun","N/D",Null,"MUB"),
("MUC","Aeroport Franz Josef Strauss","N/D",Null,"MUC"),
("MVD","Aeroport international de Carrasco","N/D",Null,"MVD"),
("MZI","Aeroport international de Mopti Ambodedjo","N/D",Null,"MZI"),
("NAN","Aeroport international de Nadi","N/D",Null,"NAN"),
("NAP","Aeroport Capodichino","N/D",1,"NAP"),
("NAS","Aeroport de Nassau","N/D",Null,"NAS"),
("NAT","Aeroport de Natal","N/D",Null,"NAT"),
("NBL","Aeroport de San Blas","N/D",Null,"NBL"),
("NBO","Aeroport international Jomo Kenyatta","N/D",Null,"NBO"),
("NCE","Aeroport de Nice-Cote d'Azur","N/D",Null,"NCE"),
("NCL","Aeroport de Newcastle","N/D",Null,"NCL"),
("NDJ","Aeroport international de N'Djamena","N/D",Null,"NDJ"),
("NEW","Aeroport Lakefront","N/D",Null,"NEW"),
("NGO","Aeroport international du Chubu","N/D",9,"NGO"),
("NGS","Aeroport international de Nagasaki","N/D",9,"NGS"),
("NIC","Aeroport de Nicosie","N/D",Null,"NIC"),
("NIM","Aeroport international Diori Hamani","N/D",Null,"NIM"),
("NKC","Aeroport international de Nouakchott","N/D",Null,"NKC"),
("NKM","Aeroport international de Nagoya","N/D",9,"NKM"),
("NOS","Aerpoort Fascene","N/D",Null,"NOS"),
("NOU","Aeroport Noumea - La Tontouta","N/D",Null,"NOU"),
("NSI","Aeroport international Nsimalen","N/D",Null,"YAO"),
("NTE","Aeroport de Nantes Atlantique","N/D",Null,"NTE"),
("NTO","Aeroport  de Santo Antao","N/D",Null,"NTO"),
("NWA","Aeroport de Moheli","N/D",Null,"NWA"),
("NWI","Aeroport international de Norwich","N/D",Null,"NWI"),
("OAK","Aeroport international d'Oakland","N/D",Null,"OAK"),
("ODB","Aeroport San Jeronimo","N/D",1,"ODB"),
("ODE","Aeroport Beldringe","N/D",Null,"ODE"),
("ODS","Aeroport Tsentrainy","N/D",Null,"ODS"),
("OHD","Aeroport d'Ohrid","N/D",Null,"OHD"),
("OLB","Aeroport Costa Smeralda","N/D",1,"OLB"),
("OMO","Aeroport de Mostar","N/D",Null,"OMO"),
("OOL","Aeroport international de Gold Coast","N/D",Null,"OOL"),
("OPO","Aeroport Pedras Rubras","N/D",0,"OPO"),
("ORD","Aeroport international O'Hare","N/D",-6,"CHI"),
("ORK","Aeroport international de Cork","N/D",Null,"ORK"),
("ORN","Aeroport d'Oran - Ahmed Ben Bella","N/D",Null,"ORA"),
("ORY","Aeroport d'orly","N/D",Null,"PAR"),
("OSL","Aeroport international d'Oslo-Gardermoen","N/D",Null,"OSL"),
("OSS","Aeroport d'Och","N/D",Null,"OSS"),
("OST","Aeroport d'Ostende-Bruges","N/D",Null,"OST"),
("OTP","Aeroport Henri Coanda","N/D",Null,"BUH"),
("OUA","Aeroport international de Ouagadougou","N/D",Null,"OUA"),
("OXB","Aeroport international Osvaldo Vieira de Bissau","N/D",Null,"BXO"),
("PAC","Aeroport Paitilla","N/D",Null,"PAC"),
("PAP","Aeroport international Toussaint Louverture","N/D",Null,"PAP"),
("PAS","Aeroport de Paros","N/D",Null,"PAS"),
("PBC","Aeroport international de Puebla","N/D",Null,"PBC"),
("PBG","Aeroport international de Plattsburgh","N/D",-5,"PBG"),
("PBH","Aeroport international de Paro","N/D",Null,"PBH"),
("PBM","Aeroport international Johan Adolf Pengel","N/D",Null,"PBM"),
("PCP","Aeroport de Principe","N/D",Null,"PCP"),
("PDX","Aeroport international de Portland","N/D",Null,"PDX"),
("PEK","Aeroport international de Pekin","N/D",8,"PEK"),
("PEN","Aeroport international de Penang","N/D",Null,"PEN"),
("PER","Aeroport de Perth","N/D",8,"PER"),
("PEW","Aeroport international de Peshawar","N/D",5,"PEW"),
("PFO","Aeroport international de Paphos","N/D",Null,"PFO"),
("PHC","Aeroport international de Port Harcourt","N/D",1,"PHC"),
("PHL","Aeroport international de Philadelphie","N/D",-5,"PHL"),
("PHW","Aeroport de Phalaborwa","N/D",Null,"PHW"),
("PHX","Aeroport international Sky Harbor","N/D",Null,"PHX"),
("PIK","Aeroport international de Glasgow Prestwick","N/D",Null,"GLA"),
("PIT","Aeroport international Greater Pittsburgh","N/D",-5,"PIT"),
("PMA","Aeroport de Pemba Island","N/D",Null,"PMA"),
("PMC","Aeroport El Tepual","N/D",Null,"PMC"),
("PMF","Aeroport de Parme","N/D",1,"PMF"),
("PMI","Aeroport de Palma de Majorque","N/D",0,"PMI"),
("PMO","Aeroport Punta Raisi","N/D",1,"PMO"),
("PNH","Aeroport international de Phnom Penh","N/D",Null,"PNH"),
("PNI","Aeroport international de Pohnpei","N/D",Null,"PNH"),
("PNR","Aeroport international Agostinho-Neto","N/D",Null,"PNR"),
("POA","Aeroport Salgado Filho","N/D",Null,"POA"),
("POI","Aeroport Capitan Nicolas Rojas","N/D",Null,"POI"),
("POL","Aeroport Porto Amelia","N/D",2,"POL"),
("POM","Aeroport de Port Moresby","N/D",Null,"POM"),
("POP","Aeroport international Gregorio-Luperon","N/D",Null,"POP"),
("POS","Aeroport de Piarco","N/D",Null,"POS"),
("PPG","Aeroport de Pago Pago","N/D",Null,"PPG"),
("PPS","Aeroport international de Puerto Princesa","N/D",8,"PPS"),
("PPT","Aeroport Faaa","N/D",Null,"PPT"),
("PRG","Aeroport de Prague-Ruzyne","N/D",Null,"PRG"),
("PRI","Aeroport de Praslin Island","N/D",Null,"PRI"),
("PRJ","Aeroport de Capri","N/D",1,"PRJ"),
("PSA","Aeroport Galilei","N/D",1,"PSA"),
("PSY","Aeroport de Port Stanley","N/D",Null,"PSY"),
("PTP","Aeroport de Pointe-a-Pitre","N/D",Null,"PTP"),
("PUJ","Aeroport international de Punta Cana","N/D",Null,"PUJ"),
("PUS","Aeroport Kimhae","N/D",9,"PUS"),
("PVR","Aeroport Lic. Gustavo D. Ordaz","N/D",Null,"PVR"),
("PYX","Aeroport de Pattaya","N/D",Null,"PYX"),
("PZU","Aeroport de Port Soudan","N/D",Null,"PZU"),
("QLS","Aeroport de Lausanne-Blecherette","N/D",Null,"QLS"),
("QTW","Aeroport de Taejon","N/D",Null,"QTW"),
("RAI","Aeroport international de Praia","N/D",Null,"RAI"),
("RAK","Aeroport de Marrakech-Menara","N/D",Null,"RAK"),
("RBA","Aeroport international de Rabat-Sale","N/D",0,"RBA"),
("RDU","Aeroport international de Raleigh-Durham","N/D",-5,"RDU"),
("REC","Aeroport Guararapes","N/D",Null,"REC"),
("REP","Aeroport international de Siem Reap-Angkor","N/D",Null,"REP"),
("RGN","Aeroport international de Yangon","N/D",Null,"RGN"),
("RHE","Aeroport Champagne","N/D",Null,"RHE"),
("RIO","Aeroport de Rio de Janeiro","N/D",Null,"RIO"),
("RIX","Aeroport international de Riga","N/D",Null,"RIX"),
("RJK","Aeroport de Rijeka","N/D",Null,"RJK"),
("ROB","Aeroport international Roberts","N/D",Null,"MLW"),
("RTB","Aeroport de Roatan","N/D",Null,"RTB"),
("RTM","Aeroport international de Rotterdam","N/D",Null,"RTM"),
("RUH","Aeroport King Khalid Airport","N/D",Null,"RUH"),
("RUN","Aeroport de Gillot","N/D",Null,"RUN"),
("RVN","Aeroport de Rovaniemi","N/D",Null,"RVN"),
("RWP","Aeroport de Rawalpindi","N/D",5,"RWP"),
("SAB","Aeroport de Saba","N/D",Null,"SAB"),
("SAH","Aeroport international El Rahaba","N/D",Null,"SAH"),
("SAL","Aeroport international de San Salvador","N/D",Null,"SAL"),
("SAO","Aeroport de Sao Paulo","N/D",Null,"SAO"),
("SAP","Aeroport international Ramon Villeda Morales","N/D",Null,"SAP"),
("SAT","Aeroport international de San Antonio","N/D",Null,"SAT"),
("SAW","Aeroport international Sabiha Gokçen d'Istanbul","N/D",2,"IST"),
("SCL","Aeroport Arturo Merino Benitez","N/D",Null,"SCL"),
("SDA","Aeroport international Saddam","N/D",3,"BGW"),
("SDQ","Aeroport international Las Americas","N/D",Null,"SDQ"),
("SEA","Aeroport international de Seattle-Tacoma","N/D",Null,"SEA"),
("SEL","Aeroport Kimpo","N/D",Null,"SEL"),
("SEZ","Aeroport international des Seychelles","N/D",Null,"SEZ"),
("SFA","Aeroport international de Sfax-Thyna","N/D",Null,"SFA"),
("SFJ","Aeroport international de Kangerlussuaq","N/D",Null,"SFJ"),
("SFO","Aeroport international de San francisco","N/D",-8,"SFO"),
("SGN","Aeroport Tan Son Nhat","N/D",7,"SGN"),
("SHA","Aeroport international de Shanghai Hongqiao","N/D",Null,"SHA"),
("SHJ","Aeroport international de Sharjah","N/D",Null,"SHA"),
("SIA","Aeroport de Xian","N/D",Null,"SIA"),
("SIN","Aeroport international Changi","N/D",Null,"SIN"),
("SJJ","Aeroport international de Sarajevo","N/D",Null,"SJJ"),
("SJO","Aeroport international Juan Santamaria de San Jose","N/D",Null,"SJO"),
("SJU","Aeroport Luis Munoz Marin","N/D",Null,"SJU"),
("SKD","Aeroport de Samarkand","N/D",Null,"SKD"),
("SKP","Aeroport de Skopje","N/D",Null,"SKP"),
("SLC","Aeroport international de Salt Lake City","N/D",Null,"SLC"),
("SMR","Aeroport international Simon Bolívar","N/D",-5,"SMR"),
("SOF","Aeroport international de Sofia","N/D",Null,"SOF"),
("SOU","Aeroport de Southampton","N/D",Null,"SOU"),
("SPK","Aeroport Chitose","N/D",9,"SPK"),
("SPN","Aeroport international de Saipan","N/D",Null,"SPN"),
("SPU","Aeroport de Split","N/D",Null,"SPU"),
("SRE","Aeroport Juana Azurduy de Padilla","N/D",Null,"SRE"),
("SSA","Aeroport Dois de Julho","N/D",Null,"SSA"),
("SSG","Aeroport de Malabo","N/D",Null,"SSG"),
("SSH","Aeroport Ras Nasrani","N/D",Null,"SSH"),
("STL","Aeroport international de Lambert-Saint Louis","N/D",Null,"STL"),
("STO","Aeroport de Stockholm","N/D",Null,"STO"),
("STR","Aeroport Echterdingen","N/D",Null,"STR"),
("SUB","Aeroport international de Surabaya","N/D",Null,"SUB"),
("SUV","Aeroport international Nausori","N/D",Null,"SUV"),
("SVG","Aeroport Sola","N/D",Null,"SVG"),
("SVO","Aeroport international Cheremetievo","N/D",3,"MOW"),
("SWP","Aeroport de Swakopmund","N/D",Null,"SWP"),
("SXB","Aeroport Entzheim","N/D",Null,"SXB"),
("SXM","Aeroport Princess Juliana","N/D",Null,"SXM"),
("SYD","Aeroport international Kingsford Smith","N/D",11,"SYD"),
("SYZ","Aeroport international de Shiraz","N/D",Null,"SYZ"),
("SZG","Aeroport Wolfgang Amadeus Mozart de Salzbourg","N/D",Null,"SZG"),
("SZX","Aeroport international de Shenzhen Bao'an","N/D",Null,"SZX"),
("TAB","Aeroport Scarborough","N/D",Null,"TAB"),
("TAH","Aeroport de Tanna Island","N/D",Null,"TAH"),
("TAS","Aeroport International de Tashkent","N/D",Null,"TAS"),
("TBS","Aeroport Novoalexeyevka","N/D",Null,"TBS"),
("TCP","Aeroport international de Taba","N/D",Null,"TCP"),
("TDD","Aeroport Teniente Jorge Henrich Arauz","N/D",Null,"TDD"),
("TER","Aeroport das Lajes","N/D",0,"TER"),
("TFN","Aeroport Los Rodeos","N/D",0,"TFN"),
("TGU","Aeroport Toncontin","N/D",Null,"TGU"),
("THR","Aeroport Qualeh Morgeh Airport","N/D",Null,"THR"),
("TIA","Aeroport international de Tirana","N/D",Null,"TIA"),
("TIP","Aeroport international de Tripoli","N/D",Null,"TIP"),
("TKU","Aeroport de Turku","N/D",Null,"TKU"),
("TLC","Aeroport Adolfo Lopez Mateos","N/D",Null,"TLC"),
("TLL","Aeroport international de Tallinn","N/D",Null,"TLL"),
("TLV","Aeroport Ben Gourion","N/D",2,"TLV"),
("TMP","Aeroport Pirkkala","N/D",Null,"TMP"),
("TMS","Aeroport international de Sao Tome","N/D",Null,"TMS"),
("TNG","Aeroport international de Tanger - Ibn Batouta","N/D",Null,"TNG"),
("TNR","Aeroport international d'Ivato","N/D",Null,"TNR"),
("TOE","Aeroport international de Tozeur-Nefta","N/D",Null,"TOE"),
("TOM","Aeroport international de Tombouctou","N/D",Null,"TOM"),
("TPE","Aeroport Chiang Kai Shek","N/D",Null,"TPE"),
("TRD","Aeroport Vaernes","N/D",Null,"TRD"),
("TRN","Aeroport Caselle","N/D",1,"TRN"),
("TSE","Aeroport International d'Astana","N/D",Null,"TSE"),
("TSN","Aeroport international de Tianjin Binhai","N/D",Null,"TSN"),
("TSR","Aeroport international Traian-Vuia de Timisoara","N/D",Null,"TSR"),
("TUN","Aeroport international de Tunis-Carthage","N/D",Null,"TUN"),
("TYO","Aeroport de Tokyo","N/D",9,"TYO"),
("TZA","Aeroport de Belize City","N/D",Null,"TZA"),
("TZL","Aeroport international de Tuzla","N/D",Null,"TZL"),
("UAK","Aeroport international de Narsarsuaq","N/D",Null,"UAK"),
("UIO","Aeroport international de Mariscal","N/D",Null,"UIO"),
("UKB","Aeroport de Kobe","N/D",9,"UKB"),
("UKY","Aeroport de Kyoto","N/D",9,"UKY"),
("ULN","Aeroport international Chinggis Khaan","N/D",Null,"ULN"),
("UPG","Aeroport international de Makassar","N/D",Null,"UPG"),
("UVE","Aeroport d'Ouvea","N/D",Null,"UVE"),
("VAP","Aeroport de Valparaiso","N/D",Null,"VAP"),
("VCA","Aeroport international de Can Tho","N/D",Null,"VCA"),
("VCE","Aeroport Marco Polo","N/D",1,"VCE"),
("VCP","Aeroport de Sao Paulo/Campinas","N/D",Null,"VCP"),
("VDA","Aeroport international Ovda","N/D",2,"VDA"),
("VFA","Aeroport de Victoria Falls","N/D",Null,"VFA"),
("VIE","Aeroport de Vienne-Schwechat","N/D",Null,"VIE"),
("VKO","Aeroport international de Vnoukovo","N/D",3,"MOW"),
("VLC","Aeroport de Valence","N/D",1,"VLC"),
("VLI","Aeroport International Bauerfield","N/D",Null,"VLI"),
("VLN","Aeroport international Arturo Michelena","N/D",Null,"VLN"),
("VNO","Aeroport international de Vilnius","N/D",Null,"VNO"),
("VNS","Aeroport de Varanasi","N/D",Null,"VNS"),
("VRA","Aeroport de Varadero","N/D",Null,"VRA"),
("VST","Aeroport de Stockholm-Vasterås","N/D",Null,"STO"),
("VTE","Aeroport international Wattay","N/D",Null,"VTE"),
("VVI","Aeroport international Viru Viru","N/D",Null,"VVI"),
("VVO","Aeroport international de Vladivostok","N/D",Null,"VVO"),
("WAS","Aeroport de Washington","N/D",-5,"WAS"),
("WDH","Aeroport international Hosea Kutako","N/D",Null,"WDH"),
("WLG","Aeroport de Wellington","N/D",Null,"WLG"),
("WLS","Aeroport Hihifo","N/D",Null,"WLS"),
("WPU","Aeroport Guardia Marina Zanartu","N/D",Null,"WPU"),
("XLS","Aeroport de Saint-Louis","N/D",Null,"XLS"),
("XQP","Aeroport de Quepos","N/D",Null,"XQP"),
("YAO","Aeroport international Nsimalen","N/D",Null,"YAO"),
("YBC","Aeroport de Baie-Comeau","N/D",-5,"YBC"),
("YBG","Aeroport de Bagotville","N/D",-5,"YBG"),
("YDA","Aeroport de Dawson","N/D",Null,"YDA"),
("YEG","Aeroport international d'Edmonton","N/D",-7,"YED"),
("YFC","Aeroport international de Fredericton","N/D",-5,"YFC"),
("YGR","Aeroport des Iles-de-la-Madeleine","N/D",-4,"YGR"),
("YHZ","Aeroport international d'Halifax","N/D",-4,"YHZ"),
("YOK","Aeroport de Yokohama","N/D",9,"YOK"),
("YOW","Aeroport Macdonald-Cartier","N/D",-5,"YOW"),
("YQB","Aeroport Jean-Lesage","N/D",-5,"YQB"),
("YQM","Aeroport international du Grand Moncton","N/D",-4,"YQM"),
("YRQ","Aeroport de Trois-Rivières","N/D",-5,"YRQ"),
("YUL","Aeroport international Pierre-Elliott-Trudeau","N/D",-5,"MTL"),
("YVA","Aeroport Hahaya/Iconi","N/D",Null,"YVA"),
("YVR","Aeroport international de Vancouver","N/D",-8,"YVR"),
("YWG","Aeroport international de Winnipeg","N/D",-6,"YWG"),
("YXY","Aeroport international de Whitehorse","N/D",Null,"YXY"),
("YYC","Aeroport international de Calgary","N/D",-7,"YYC"),
("YYZ","Aeroport international Lester B. Pearson","N/D",-5,"YTO"),
("ZAD","Aeroport de Zadar","N/D",Null,"ZAD"),
("ZAG","Aeroport Pleso","N/D",Null,"ZAG"),
("ZAM","Aeroport international de Zamboanga","N/D",8,"ZAM"),
("ZGC","Aeroport de Lanzhou","N/D",Null,"ZGC"),
("ZIG","Aeroport de Ziguinchor","N/D",Null,"ZIG");
